version: '3.4'
services:
  metad:
    image: vesoft/nebula-metad:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.29.1.1:45500
      - --local_ip=172.29.1.1
      - --ws_ip=172.29.1.1
      - --port=45500
    volumes:
      - metadata:/usr/local/nebula/data/meta
      - logsdata:/usr/local/nebula/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.29.1.1:11000/status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 11000
      - 11002
    networks:
      nebula-net:
        ipv4_address: 172.29.1.1
    restart: on-failure

  storaged:
    image: vesoft/nebula-storaged:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.29.1.1:45500
      - --local_ip=172.29.2.1
      - --ws_ip=172.29.2.1
      - --port=44500
    volumes:
      - storagedata:/usr/local/nebula/data/storage
      - logsdata:/usr/local/nebula/logs
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.29.2.1:12000/status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 12000
      - 12002
    networks:
      nebula-net:
        ipv4_address: 172.29.2.1
    restart: on-failure

  graphd1:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.29.1.1:45500
      - --port=3699
      - --ws_ip=172.29.3.1
      - --log_dir=/usr/local/nebula/logs1
    volumes:
      - logsdata:/usr/local/nebula/logs1
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.29.3.1:13000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 3699
      - 13000
      - 13002
    networks:
      nebula-net:
        ipv4_address: 172.29.3.1
    restart: on-failure

  graphd2:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.29.1.1:45500
      - --port=3699
      - --ws_ip=172.29.3.2
      - --log_dir=/usr/local/nebula/logs2
      - --enable_authorize=true
    volumes:
      - logsdata:/usr/local/nebula/logs2
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.29.3.2:13000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 3699
      - 13000
      - 13002
    networks:
      nebula-net:
        ipv4_address: 172.29.3.2
    restart: on-failure

  importer:
    image: vesoft/nebula-console:nightly
    volumes:
      - .:/usr/local/nebula/importer:rw
    entrypoint:
      - ./importer/ci/bootstrap.sh
      - "172.29.3.1"
      - "3699"
    depends_on:
      - graphd1
      - graphd2
    networks:
      nebula-net:
        ipv4_address: 172.29.4.1

networks:
  nebula-net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  storagedata:
  metadata:
  logsdata:
