version: '3.4'
services:
  metad:
    image: vesoft/nebula-metad:nightly
    environment:
      USER: root
      TZ: UTC
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=metad
      - --ws_ip=metad
      - --port=9559
      - --ws_http_port=19559
    healthcheck:
      test: ["CMD", "curl", "-f", "http://metad:19559/status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9559
      - 19559
      - 19560
    networks:
      nebula-net:
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged:
    image: vesoft/nebula-storaged:nightly
    environment:
      USER: root
      TZ: UTC
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=storaged
      - --ws_ip=storaged
      - --port=9779
      - --ws_http_port=19779
      - --local_config=false
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storaged:19779/status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9779
      - 19779
      - 19780
    networks:
      nebula-net:
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd1:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
      TZ: UTC
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=graphd1
      - --ws_ip=graphd1
      - --port=9669
      - --ws_http_port=19669
      - --local_config=false
    depends_on:
      - metad
      - storaged
    healthcheck:
      test: ["CMD", "curl", "-f", "http://graphd1:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9669
      - 19669
      - 19670
    networks:
      nebula-net:
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd2:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
      TZ: UTC
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=graphd1
      - --ws_ip=graphd2
      - --port=9669
      - --ws_http_port=19669
      - --enable_authorize=true
      - --local_config=false
    depends_on:
      - metad
      - storaged
    healthcheck:
      test: ["CMD", "curl", "-f", "http://graphd2:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9669
      - 19669
      - 19670
    networks:
      nebula-net:
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  importer:
    image: golang:alpine
    volumes:
      - .:/usr/local/nebula/importer:rw
    working_dir: /usr/local/nebula
    entrypoint:
      - ./importer/ci/bootstrap.sh
      - "graphd1"
      - "9669"
    depends_on:
      - graphd1
      - graphd2
    networks:
      nebula-net:

networks:
  nebula-net:
